// Code generated by MockGen. DO NOT EDIT.
// Source: access.go
//
// Generated by this command:
//
//	mockgen -source=access.go -destination=access_mocks.go -package=ports
//

// Package ports is a generated GoMock package.
package ports

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTmpTokenManager is a mock of TmpTokenManager interface.
type MockTmpTokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockTmpTokenManagerMockRecorder
	isgomock struct{}
}

// MockTmpTokenManagerMockRecorder is the mock recorder for MockTmpTokenManager.
type MockTmpTokenManagerMockRecorder struct {
	mock *MockTmpTokenManager
}

// NewMockTmpTokenManager creates a new mock instance.
func NewMockTmpTokenManager(ctrl *gomock.Controller) *MockTmpTokenManager {
	mock := &MockTmpTokenManager{ctrl: ctrl}
	mock.recorder = &MockTmpTokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTmpTokenManager) EXPECT() *MockTmpTokenManagerMockRecorder {
	return m.recorder
}

// GenerateTmpToken mocks base method.
func (m *MockTmpTokenManager) GenerateTmpToken(payload map[string]string, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTmpToken", payload, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTmpToken indicates an expected call of GenerateTmpToken.
func (mr *MockTmpTokenManagerMockRecorder) GenerateTmpToken(payload, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTmpToken", reflect.TypeOf((*MockTmpTokenManager)(nil).GenerateTmpToken), payload, ttl)
}

// ValidateTmpToken mocks base method.
func (m *MockTmpTokenManager) ValidateTmpToken(tmpToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTmpToken", tmpToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateTmpToken indicates an expected call of ValidateTmpToken.
func (mr *MockTmpTokenManagerMockRecorder) ValidateTmpToken(tmpToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTmpToken", reflect.TypeOf((*MockTmpTokenManager)(nil).ValidateTmpToken), tmpToken)
}
