// Code generated by MockGen. DO NOT EDIT.
// Source: profile.go
//
// Generated by this command:
//
//	mockgen -source=profile.go -destination=profile_mocks.go -package=ports
//

// Package ports is a generated GoMock package.
package ports

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProfileProvider is a mock of ProfileProvider interface.
type MockProfileProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProfileProviderMockRecorder
	isgomock struct{}
}

// MockProfileProviderMockRecorder is the mock recorder for MockProfileProvider.
type MockProfileProviderMockRecorder struct {
	mock *MockProfileProvider
}

// NewMockProfileProvider creates a new mock instance.
func NewMockProfileProvider(ctrl *gomock.Controller) *MockProfileProvider {
	mock := &MockProfileProvider{ctrl: ctrl}
	mock.recorder = &MockProfileProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileProvider) EXPECT() *MockProfileProviderMockRecorder {
	return m.recorder
}

// GetExtraClaims mocks base method.
func (m *MockProfileProvider) GetExtraClaims(ctx context.Context, email string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExtraClaims", ctx, email)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExtraClaims indicates an expected call of GetExtraClaims.
func (mr *MockProfileProviderMockRecorder) GetExtraClaims(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExtraClaims", reflect.TypeOf((*MockProfileProvider)(nil).GetExtraClaims), ctx, email)
}
